virtual bool openvip(VipLevel vl);
virtual bool requestPhoto();
virtual bool ping();
virtual bool sessionlogin(COM_LoginInfo& info);
virtual bool login(COM_LoginInfo& info);
virtual bool createPlayer(std::string& playername, uint8_t playerTmpId);
virtual bool deletePlayer(std::string& playername);
virtual bool enterGame(uint32_t playerInstId);
virtual bool requestBag();
virtual bool requestEmployees();
virtual bool requestStorage(StorageType tp);
virtual bool requestAchievement();
virtual bool initminig();
virtual bool requestCompound();
virtual bool move(float x, float z);
virtual bool moveToNpc(int32_t npcid);
virtual bool moveToNpc2(NpcType type);
virtual bool moveToZone(int32_t sceneId, int32_t zoneId);
virtual bool autoBattle();
virtual bool stopAutoBattle();
virtual bool stopMove();
virtual bool exitCopy();
virtual bool transforScene(int32_t sceneId);
virtual bool sceneLoaded();
virtual bool querySimplePlayerInst(uint32_t instId);
virtual bool logout();
virtual bool changProp(uint32_t guid, std::vector< COM_Addprop >& props);
virtual bool learnSkill(uint32_t skid);
virtual bool babyLearnSkill(uint32_t instId, uint32_t oldSkId, uint32_t newSkId, uint32_t newSkLv);
virtual bool forgetSkill(uint32_t skid);
virtual bool syncOrder(COM_Order& order);
virtual bool syncOrderTimeout();
virtual bool sendChat(COM_Chat& content, std::string& targetName);
virtual bool requestAudio(int32_t audioId);
virtual bool publishItemInst(ItemContainerType type, uint32_t itemInstId, ChatKind chatType, std::string& playerName);
virtual bool queryItemInst(int32_t showId);
virtual bool publishbabyInst(ChatKind type, uint32_t babyInstId, std::string& playerName);
virtual bool querybabyInst(int32_t showId);
virtual bool useItem(uint32_t slot, uint32_t target, uint32_t stack);
virtual bool wearEquipment(uint32_t target, uint32_t itemInstId);
virtual bool delEquipment(uint32_t target, uint32_t itemInstId);
virtual bool setPlayerFront(bool isFront);
virtual bool setBattlebaby(uint32_t babyID, bool isBattle);
virtual bool changeBabyName(uint32_t babyID, std::string& name);
virtual bool intensifyBaby(uint32_t babyid);
virtual bool setBattleEmp(uint32_t empID, EmployeesBattleGroup group, bool isBattle);
virtual bool changeEmpBattleGroup(EmployeesBattleGroup group);
virtual bool requestEvolve(uint32_t empInstId);
virtual bool requestUpStar(uint32_t empInstId);
virtual bool requestDelEmp(uint32_t empInstId);
virtual bool delEmployee(std::vector< uint32_t >& emps);
virtual bool onekeyDelEmp();
virtual bool delEmployeeSoul(uint32_t instid, uint32_t soulNum);
virtual bool sortBagItem();
virtual bool sellBagItem(uint32_t instId, uint32_t stack);
virtual bool depositItemToStorage(uint32_t instid);
virtual bool depositBabyToStorage(uint32_t instid);
virtual bool storageItemToBag(uint32_t instid);
virtual bool storageBabyToPlayer(uint32_t instid);
virtual bool sortStorage(StorageType tp);
virtual bool delStorageBaby(uint32_t instid);
virtual bool jointLobby();
virtual bool exitLobby();
virtual bool createTeam(COM_CreateTeamInfo& cti);
virtual bool changeTeam(COM_CreateTeamInfo& info);
virtual bool kickTeamMember(uint32_t uuid);
virtual bool changeTeamLeader(uint32_t uuid);
virtual bool joinTeam(uint32_t teamId, std::string& pwd);
virtual bool exitTeam();
virtual bool changeTeamPassword(std::string& pwd);
virtual bool joinTeamRoom();
virtual bool inviteTeamMember(std::string& name);
virtual bool isjoinTeam(uint32_t teamId, bool isFlag);
virtual bool leaveTeam();
virtual bool backTeam();
virtual bool refuseBackTeam();
virtual bool teamCallMember(int32_t playerId);
virtual bool requestJoinTeam(std::string& targetName);
virtual bool ratifyJoinTeam(std::string& sendName);
virtual bool drawLotteryBox(BoxType type, bool isFree);
virtual bool acceptQuest(int32_t questId);
virtual bool submitQuest(int32_t npcId, int32_t questId);
virtual bool giveupQuest(int32_t questId);
virtual bool requestContactInfoById(uint32_t instId);
virtual bool requestContactInfoByName(std::string& instName);
virtual bool requestFriendList();
virtual bool addFriend(uint32_t instId);
virtual bool delFriend(uint32_t instId);
virtual bool addBlacklist(uint32_t instId);
virtual bool delBlacklist(uint32_t instId);
virtual bool requestReferrFriend();
virtual bool mining(int32_t gatherId, int32_t times);
virtual bool compoundItem(int32_t itemId, int32_t gemId);
virtual bool bagItemSplit(int32_t instId, int32_t splitNum);
virtual bool requestChallenge(std::string& name);
virtual bool requestRival();
virtual bool requestMySelfJJCData();
virtual bool requestCheckMsg(std::string& name);
virtual bool requestMyAllbattleMsg();
virtual bool requestJJCRank();
virtual bool requestLevelRank();
virtual bool requestBabyRank();
virtual bool requestEmpRank();
virtual bool requestPlayerFFRank();
virtual bool queryOnlinePlayerbyName(std::string& name);
virtual bool queryPlayerbyName(std::string& name);
virtual bool queryBaby(uint32_t instId);
virtual bool queryEmployee(uint32_t instId);
virtual bool guideFinish(uint64_t guideIdx);
virtual bool enterBattle(int32_t battleId);
virtual bool shopBuyItem(int32_t id, int32_t num);
virtual bool getFirstRechargeItem();
virtual bool requestLevelGift(int32_t level);
virtual bool setCurrentTitle(int32_t title);
virtual bool openBuyBox();
virtual bool requestAchaward(int32_t achId);
virtual bool sign(int32_t index);
virtual bool requestSignupReward7();
virtual bool requestSignupReward14();
virtual bool requestSignupReward28();
virtual bool requestActivityReward(int32_t index);
virtual bool resetHundredTier();
virtual bool enterHundredScene(int32_t level);
virtual bool delBaby(int32_t instId);
virtual bool resetBaby(int32_t instId);
virtual bool resetBabyProp(int32_t instId);
virtual bool remouldBaby(int32_t instid);
virtual bool empSkillLevelUp(uint32_t empId, int32_t skillId);
virtual bool setOpenDoubleTimeFlag(bool isFlag);
virtual bool talkedNpc(int32_t npcId);
virtual bool jjcBattleGo(uint32_t id);
virtual bool requestMyJJCTeamMsg();
virtual bool startMatching();
virtual bool stopMatching();
virtual bool exitPvpJJC();
virtual bool joinPvpLobby();
virtual bool exitPvpLobby();
virtual bool requestpvprank();
virtual bool joinWarriorchoose();
virtual bool warriorStart();
virtual bool warriorStop();
virtual bool sendMail(std::string& playername, std::string& title, std::string& content);
virtual bool readMail(int32_t mailId);
virtual bool delMail(int32_t mailId);
virtual bool getMailItem(int32_t mailId);
virtual bool requestState();
virtual bool createGuild(std::string& guildName);
virtual bool delGuild(uint32_t guildId);
virtual bool requestJoinGuild(uint32_t guid);
virtual bool leaveGuild();
virtual bool kickOut(int32_t guid);
virtual bool acceptRequestGuild(int32_t playerId);
virtual bool refuseRequestGuild(int32_t playerId);
virtual bool changeMemberPosition(int32_t targetId, GuildJob job);
virtual bool transferPremier(int32_t targetId);
virtual bool changeGuildNotice(std::string& notice);
virtual bool queryGuildList(int16_t page);
virtual bool inviteJoinGuild(std::string& playerName);
virtual bool respondInviteJoinGuild(std::string& sendName);
virtual bool buyGuildItem(int32_t tableId, int32_t times);
virtual bool entryGuildBattle();
virtual bool transforGuildBattleScene();
virtual bool addGuildMoney(int32_t money);
virtual bool updateGuildBuiling(GuildBuildingType gbt);
virtual bool refreshGuildShop();
virtual bool levelupGuildSkill(int32_t skId);
virtual bool presentGuildItem(int32_t num);
virtual bool progenitusAddExp(int32_t monsterId, bool isSuper);
virtual bool setProgenitusPosition(int32_t mId, int32_t pos);
virtual bool guildsign();
virtual bool fetchSelling(COM_SearchContext& context);
virtual bool fetchSelling2(COM_SearchContext& context);
virtual bool selling(int32_t iteminstid, int32_t babyinstid, int32_t price);
virtual bool unselling(int32_t sellid);
virtual bool buy(int32_t sellid);
virtual bool fixItem(int32_t instId, FixType type);
virtual bool fixAllItem(std::vector< uint32_t >& items, FixType type);
virtual bool makeDebirsItem(int32_t instId, int32_t num);
virtual bool levelUpMagicItem(std::vector< uint32_t >& items);
virtual bool tupoMagicItem(int32_t level);
virtual bool changeMagicJob(JobType job);
virtual bool requestPk(uint32_t playerId);
virtual bool uiBehavior(UIBehaviorType type);
virtual bool openZhuanpan();
virtual bool zhuanpanGo(uint32_t counter);
virtual bool redemptionSpree(std::string& code);
virtual bool sceneFilter(std::vector< SceneFilterType >& sfType);
virtual bool sendExamAnswer(uint32_t questionId, uint8_t answer);
virtual bool sendwishing(COM_Wishing& wish);
virtual bool requestWish();
virtual bool leaderCloseDialog();
virtual bool requestOnlineReward(uint32_t index);
virtual bool requestFundReward(uint32_t level);
virtual bool openCard(uint16_t index);
virtual bool resetCard();
virtual bool hotRoleBuy();
virtual bool requestSevenReward(uint32_t qid);
virtual bool vipreward();
virtual bool requestChargeTotalSingleReward(uint32_t index);
virtual bool requestChargeTotalReward(uint32_t index);
virtual bool requestChargeEverySingleReward(uint32_t index);
virtual bool requestChargeEveryReward(uint32_t index);
virtual bool requestLoginTotal(uint32_t index);
virtual bool buyDiscountStoreSingle(int32_t itemId, int32_t itemStack);
virtual bool buyDiscountStore(int32_t itemId, int32_t itemStack);
virtual bool requestEmployeeActivityReward(uint32_t index);
virtual bool requestmyselfrechargeleReward(uint32_t index);
virtual bool requestEverydayIntegral();
virtual bool buyIntegralItem(uint32_t id, uint32_t num);
virtual bool familyLoseLeader();
virtual bool verificationSMS(std::string& phoneNumber, std::string& code);
virtual bool lockItem(int32_t instId, bool isLock);
virtual bool lockBaby(int32_t instId, bool isLock);
virtual bool showBaby(int32_t instId);
virtual bool wearFuwen(int32_t itemInstId);
virtual bool takeoffFuwen(int32_t slotId);
virtual bool compFuwen(int32_t itemInstId);
virtual bool requestEmployeeQuest();
virtual bool acceptEmployeeQuest(int32_t questId, std::vector< int32_t >& employees);
virtual bool submitEmployeeQuest(int32_t questId);
virtual bool crystalUpLevel();
virtual bool resetCrystalProp(std::vector< int32_t >& locklist);
virtual bool magicItemOneKeyLevel();
virtual bool submitQuest2(int32_t npcId, int32_t questId, int32_t instId);
