virtual bool pong();
virtual bool errorno(ErrorNo e);
virtual bool teamerrorno(std::string& name, ErrorNo e);
virtual bool reconnection(COM_ReconnectInfo& recInfo);
virtual bool sessionfailed();
virtual bool loginok(std::string& sessionkey, std::vector< COM_SimpleInformation >& players);
virtual bool logoutOk();
virtual bool createPlayerOk(COM_SimpleInformation& player);
virtual bool deletePlayerOk(std::string& name);
virtual bool enterGameOk(COM_PlayerInst& inst);
virtual bool initBabies(std::vector< COM_BabyInst >& insts);
virtual bool initEmployees(std::vector< COM_EmployeeInst >& insts, bool isFlag);
virtual bool initEmpBattleGroup(COM_BattleEmp& bep);
virtual bool initNpc(std::vector< int32_t >& npcList);
virtual bool initAchievement(std::vector< COM_Achievement >& actlist);
virtual bool initGather(uint32_t allnum, std::vector< COM_Gather >& gathers);
virtual bool initcompound(std::vector< uint32_t >& compounds);
virtual bool addBaby(COM_BabyInst& inst);
virtual bool refreshBaby(COM_BabyInst& inst);
virtual bool delBabyOK(uint32_t babyInstId);
virtual bool changeBabyNameOK(uint32_t babyId, std::string& name);
virtual bool remouldBabyOK(uint32_t instid);
virtual bool intensifyBabyOK(uint32_t babyid, uint32_t intensifyLevel);
virtual bool learnSkillOk(COM_Skill& inst);
virtual bool forgetSkillOk(uint32_t skid);
virtual bool addSkillExp(uint32_t skid, uint32_t uExp, ItemUseFlag flag);
virtual bool babyLearnSkillOK(uint32_t instId, uint32_t newSkId);
virtual bool skillLevelUp(uint32_t instId, COM_Skill& inst);
virtual bool joinScene(COM_SceneInfo& info);
virtual bool joinCopySceneOK(int32_t secneid);
virtual bool initCopyNums();
virtual bool addToScene(COM_ScenePlayerInformation& inst);
virtual bool delFormScene(int32_t instId);
virtual bool move2(int32_t instId, COM_FPosition& pos);
virtual bool cantMove();
virtual bool querySimplePlayerInstOk(COM_SimplePlayerInst& player);
virtual bool transfor2(int32_t instId, COM_FPosition& pos);
virtual bool openScene(int32_t sceneId);
virtual bool autoBattleResult(bool isOk);
virtual bool talked2Npc(int32_t npcId);
virtual bool talked2Player(int32_t playerId);
virtual bool useItemOk(int32_t itemId, int32_t stack);
virtual bool syncBattleStatus(int32_t playerId, bool inBattle);
virtual bool enterBattleOk(COM_InitBattle& initBattle);
virtual bool exitBattleOk(BattleJudgeType bjt, COM_BattleOverClearing& init);
virtual bool syncOrderOk(uint32_t uid);
virtual bool syncOrderOkEX();
virtual bool syncOneTurnAction(COM_BattleReport& reports);
virtual bool syncProperties(uint32_t guid, std::vector< COM_PropValue >& props);
virtual bool receiveChat(COM_ChatInfo& info, COM_ContactInfo& myinfo);
virtual bool requestAudioOk(int32_t audioId, std::vector< uint8_t >& content);
virtual bool publishItemInstRes(COM_ShowItemInstInfo& info, ChatKind type);
virtual bool queryItemInstRes(COM_ShowItemInst& item);
virtual bool publishBabyInstRes(COM_ShowbabyInstInfo& info, ChatKind type);
virtual bool queryBabyInstRes(COM_ShowbabyInst& inst);
virtual bool setNoTalkTime(float t);
virtual bool addNpc(std::vector< int32_t >& npcList);
virtual bool delNpc(std::vector< int32_t >& npcList);
virtual bool setTeamLeader(int32_t playerId, bool isLeader);
virtual bool initBag(std::vector< COM_Item >& items);
virtual bool addBagItem(COM_Item& item);
virtual bool delBagItem(uint16_t slot);
virtual bool updateBagItem(COM_Item& item);
virtual bool depositItemOK(COM_Item& item);
virtual bool getoutItemOK(uint16_t slot);
virtual bool depositBabyOK(COM_BabyInst& baby);
virtual bool getoutBabyOK(uint16_t slot);
virtual bool sortItemStorageOK(std::vector< COM_Item >& items);
virtual bool sortBabyStorageOK(std::vector< uint32_t >& babys);
virtual bool initItemStorage(uint16_t gridNum, std::vector< COM_Item >& items);
virtual bool initBabyStorage(uint16_t gridNum, std::vector< COM_BabyInst >& babys);
virtual bool openStorageGrid(StorageType tp, uint16_t gridNum);
virtual bool delStorageBabyOK(uint16_t slot);
virtual bool initPlayerEquips(std::vector< COM_Item >& equips);
virtual bool wearEquipmentOk(uint32_t target, COM_Item& equip);
virtual bool scenePlayerWearEquipment(uint32_t target, uint32_t itemId);
virtual bool delEquipmentOk(uint32_t target, uint32_t itemInstId);
virtual bool scenePlayerDoffEquipment(uint32_t target, uint32_t itemId);
virtual bool sortBagItemOk();
virtual bool jointLobbyOk(std::vector< COM_SimpleTeamInfo >& infos);
virtual bool exitLobbyOk();
virtual bool syncDelLobbyTeam(uint32_t teamId);
virtual bool syncUpdateLobbyTeam(COM_SimpleTeamInfo& info);
virtual bool syncAddLobbyTeam(COM_SimpleTeamInfo& team);
virtual bool createTeamOk(COM_TeamInfo& team);
virtual bool changeTeamOk(COM_TeamInfo& team);
virtual bool joinTeamOk(COM_TeamInfo& team);
virtual bool addTeamMember(COM_SimplePlayerInst& info);
virtual bool delTeamMember(int32_t instId);
virtual bool changeTeamLeaderOk(int32_t uuid);
virtual bool exitTeamOk(bool iskick);
virtual bool updateTeam(COM_TeamInfo& team);
virtual bool joinTeamRoomOK(COM_TeamInfo& team);
virtual bool inviteJoinTeam(uint32_t teamId, std::string& name);
virtual bool syncTeamDirtyProp(int32_t guid, std::vector< COM_PropValue >& props);
virtual bool leaveTeamOk(int32_t playerId);
virtual bool backTeamOK(int32_t playerId);
virtual bool teamCallMemberBack();
virtual bool refuseBackTeamOk(int32_t playerId);
virtual bool requestJoinTeamTranspond(std::string& reqName);
virtual bool drawLotteryBoxRep(std::vector< COM_Item >& items);
virtual bool addEmployee(COM_EmployeeInst& employee);
virtual bool battleEmployee(int32_t empId, EmployeesBattleGroup group, bool forbattle);
virtual bool changeEmpBattleGroupOK(EmployeesBattleGroup group);
virtual bool evolveOK(int32_t guid, QualityColor qc);
virtual bool upStarOK(int32_t guid, int32_t star, COM_Skill& sk);
virtual bool delEmployeeOK(std::vector< uint32_t >& instids);
virtual bool sycnEmployeeSoul(int32_t guid, uint32_t soulNum);
virtual bool initQuest(std::vector< COM_QuestInst >& qlist, std::vector< int32_t >& clist);
virtual bool acceptQuestOk(COM_QuestInst& inst);
virtual bool submitQuestOk(int32_t questId);
virtual bool giveupQuestOk(int32_t questId);
virtual bool updateQuestInst(COM_QuestInst& inst);
virtual bool requestContactInfoOk(COM_ContactInfo& contact);
virtual bool addFriendOK(COM_ContactInfo& inst);
virtual bool delFriendOK(uint32_t instId);
virtual bool addBlacklistOK(COM_ContactInfo& inst);
virtual bool delBlacklistOK(uint32_t instId);
virtual bool findFriendFail();
virtual bool referrFriendOK(std::vector< COM_ContactInfo >& insts);
virtual bool requestFriendListOK(std::vector< COM_ContactInfo >& insts);
virtual bool lotteryOk(int32_t lotteryId, std::vector< COM_DropItem >& dropItem);
virtual bool openGatherOK(COM_Gather& gather);
virtual bool miningOk(std::vector< COM_DropItem >& items, COM_Gather& gather, uint32_t gatherNum);
virtual bool openCompound(uint32_t compoundId);
virtual bool compoundItemOk(COM_Item& item);
virtual bool openBagGridOk(int32_t num);
virtual bool requestChallengeOK(bool isOK);
virtual bool requestMySelfJJCDataOK(COM_EndlessStair& info);
virtual bool requestRivalOK(std::vector< COM_EndlessStair >& infos);
virtual bool rivalTimeOK();
virtual bool checkMsgOK(COM_SimplePlayerInst& inst);
virtual bool requestMyAllbattleMsgOK(std::vector< COM_JJCBattleMsg >& infos);
virtual bool myBattleMsgOK(COM_JJCBattleMsg& info);
virtual bool requestJJCRankOK(uint32_t myRank, std::vector< COM_EndlessStair >& infos);
virtual bool requestLevelRankOK(uint32_t myRank, std::vector< COM_ContactInfo >& infos);
virtual bool requestBabyRankOK(uint32_t myRank, std::vector< COM_BabyRankData >& infos);
virtual bool requestEmpRankOK(uint32_t myRank, std::vector< COM_EmployeeRankData >& infos);
virtual bool requestPlayerFFRankOK(uint32_t myRank, std::vector< COM_ContactInfo >& infos);
virtual bool queryOnlinePlayerOK(bool isOnline);
virtual bool queryPlayerOK(COM_SimplePlayerInst& inst);
virtual bool queryBabyOK(COM_BabyInst& inst);
virtual bool queryEmployeeOK(COM_EmployeeInst& inst);
virtual bool initGuide(uint32_t guideMask);
virtual bool buyShopItemOk(int32_t id);
virtual bool addPlayerTitle(int32_t title);
virtual bool delPlayerTitle(int32_t title);
virtual bool requestOpenBuyBox(float greenTime, float blueTime, int32_t greenFreeNum);
virtual bool requestGreenBoxTimeOk();
virtual bool requestBlueBoxTimeOk();
virtual bool updateAchievementinfo(COM_Achievement& achs);
virtual bool syncOpenSystemFlag(uint64_t flag);
virtual bool requestActivityRewardOK(uint32_t ar);
virtual bool syncActivity(COM_ActivityTable& table);
virtual bool updateActivityStatus(ActivityType type, bool open);
virtual bool updateActivityCounter(ActivityType type, int32_t counter, int32_t reward);
virtual bool syncExam(COM_Exam& exam);
virtual bool syncExamAnswer(COM_Answer& answer);
virtual bool petActivityNoNum(std::string& name);
virtual bool syncHundredInfo(COM_HundredBattle& hb);
virtual bool initSignUp(std::vector< int32_t >& info, int32_t process, bool sign7, bool sign14, bool sign28);
virtual bool signUp(bool flag);
virtual bool requestSignupRewardOk7();
virtual bool requestSignupRewardOk14();
virtual bool requestSignupRewardOk28();
virtual bool sycnDoubleExpTime(bool isFlag, float times);
virtual bool sycnStates(std::vector< COM_State >& states);
virtual bool requestpvprankOK(std::vector< COM_ContactInfo >& infos);
virtual bool syncMyJJCTeamMember();
virtual bool startMatchingOK();
virtual bool stopMatchingOK(float times);
virtual bool updatePvpJJCinfo(COM_PlayerVsPlayer& info);
virtual bool exitPvpJJCOk();
virtual bool syncEnemyPvpJJCPlayerInfo(COM_SimpleInformation& info);
virtual bool syncEnemyPvpJJCTeamInfo(std::vector< COM_SimpleInformation >& infos, uint32_t teamID_);
virtual bool openWarriorchooseUI();
virtual bool warriorStartOK();
virtual bool warriorStopOK();
virtual bool syncWarriorEnemyTeamInfo(std::vector< COM_SimpleInformation >& infos, uint32_t teamID_);
virtual bool appendMail(std::vector< COM_Mail >& mails);
virtual bool delMail(int32_t mailId);
virtual bool updateMailOk(COM_Mail& mail);
virtual bool boardcastNotice(std::string& content, bool isGm);
virtual bool createGuildOK();
virtual bool delGuildOK();
virtual bool leaveGuildOk(std::string& who, bool isKick);
virtual bool initGuildData(COM_Guild& guild);
virtual bool initGuildMemberList(std::vector< COM_GuildMember >& member);
virtual bool modifyGuildMemberList(COM_GuildMember& member, ModifyListFlag flag);
virtual bool modifyGuildList(COM_GuildViewerData& data, ModifyListFlag flag);
virtual bool queryGuildListResult(int16_t page, int16_t pageNum, std::vector< COM_GuildViewerData >& guildList);
virtual bool inviteGuild(std::string& sendName, std::string& guildName);
virtual bool updateGuildShopItems(std::vector< COM_GuildShopItem >& items);
virtual bool updateGuildBuilding(GuildBuildingType type, COM_GuildBuilding& building);
virtual bool updateGuildMyMember(COM_GuildMember& member);
virtual bool levelupGuildSkillOk(COM_Skill& skInst);
virtual bool presentGuildItemOk(int32_t val);
virtual bool progenitusAddExpOk(COM_GuildProgen& mInst);
virtual bool setProgenitusPositionOk(std::vector< int32_t >& positions);
virtual bool updateGuildFundz(int32_t val);
virtual bool updateGuildMemberContribution(int32_t val);
virtual bool openGuildBattle(std::string& otherName, int32_t playerNum, int32_t level, bool isLeft, int32_t lstime);
virtual bool startGuildBattle(std::string& otherName, int32_t otherCon, int32_t selfCon);
virtual bool closeGuildBattle(bool isWinner);
virtual bool syncGuildBattleWinCount(int32_t myWin, int32_t otherWin);
virtual bool initMySelling(std::vector< COM_SellItem >& items);
virtual bool initMySelled(std::vector< COM_SelledItem >& items);
virtual bool fetchSellingOk(std::vector< COM_SellItem >& items, int32_t total);
virtual bool fetchSellingOk2(std::vector< COM_SellItem >& items, int32_t total);
virtual bool sellingOk(COM_SellItem& item);
virtual bool selledOk(COM_SelledItem& item);
virtual bool unsellingOk(int32_t sellid);
virtual bool redemptionSpreeOk();
virtual bool insertState(COM_State& st);
virtual bool updattState(COM_State& st);
virtual bool removeState(uint32_t stid);
virtual bool requestFixItemOk(COM_Item& item);
virtual bool makeDebirsItemOK();
virtual bool updateMagicItem(int32_t level, int32_t exp);
virtual bool changeMagicJobOk(JobType job);
virtual bool magicItemTupoOk(int32_t level);
virtual bool zhuanpanOK(std::vector< uint32_t >& pond);
virtual bool updateZhuanpanNotice(COM_Zhuanpan& zhuanp);
virtual bool sycnZhuanpanData(COM_ZhuanpanData& data);
virtual bool copynonum(std::string& name);
virtual bool sceneFilterOk(std::vector< SceneFilterType >& sfType);
virtual bool wishingOK();
virtual bool shareWishOK(COM_Wish& wish);
virtual bool leaderCloseDialogOk();
virtual bool startOnlineTime();
virtual bool requestOnlineTimeRewardOK(uint32_t index);
virtual bool sycnVipflag(bool flag);
virtual bool buyFundOK(bool flag);
virtual bool requestFundRewardOK(uint32_t level);
virtual bool firstRechargeOK(bool isFlag);
virtual bool firstRechargeGiftOK(bool isFlag);
virtual bool agencyActivity(ADType type, bool isFlag);
virtual bool updateFestival(COM_ADLoginTotal& festival);
virtual bool updateSelfRecharge(COM_ADChargeTotal& val);
virtual bool updateSysRecharge(COM_ADChargeTotal& val);
virtual bool updateSelfDiscountStore(COM_ADDiscountStore& val);
virtual bool updateSysDiscountStore(COM_ADDiscountStore& val);
virtual bool updateSelfOnceRecharge(COM_ADChargeEvery& val);
virtual bool updateSysOnceRecharge(COM_ADChargeEvery& val);
virtual bool openCardOK(COM_ADCardsContent& data);
virtual bool resetCardOK();
virtual bool sycnHotRole(COM_ADHotRole& data);
virtual bool hotRoleBuyOk(uint16_t buyNum);
virtual bool updateSevenday(COM_Sevenday& data);
virtual bool updateEmployeeActivity(COM_ADEmployeeTotal& data);
virtual bool updateMinGiftActivity(COM_ADGiftBag& data);
virtual bool updateIntegralShop(COM_IntegralData& data);
virtual bool updateShowBaby(uint32_t playerId, uint32_t showBabyTableId, std::string& showBabyName);
virtual bool updateMySelfRecharge(COM_ADChargeTotal& val);
virtual bool verificationSMSOk(std::string& phoneNumber);
virtual bool requestLevelGiftOK(int32_t level);
virtual bool sycnConvertExp(int32_t val);
virtual bool wearFuwenOk(COM_Item& inst);
virtual bool takeoffFuwenOk(int32_t slot);
virtual bool compFuwenOk();
virtual bool requestEmployeeQuestOk(std::vector< COM_EmployeeQuestInst >& questList);
virtual bool acceptEmployeeQuestOk(COM_EmployeeQuestInst& inst);
virtual bool submitEmployeeQuestOk(int32_t questId, bool isSuccess);
virtual bool sycnCrystal(COM_CrystalData& data);
virtual bool crystalUpLeveResult(bool isOK);
virtual bool resetCrystalPropOK();
virtual bool sycnCourseGift(std::vector< COM_CourseGift >& data);
virtual bool orderOk(std::string& orderId, int32_t shopId);
virtual bool updateRandSubmitQuestCount(int32_t submitCount);
virtual bool updateTeamMember(int32_t playerId, bool isMember);
