virtual bool initScenePlayer(SGE_ScenePlayerInfo& info);
virtual bool scenePlayerUpLevel(int32_t level);
virtual bool scenePlayerAddCurrentQuest(int32_t questId);
virtual bool scenePlayerDelCurrentQuest(int32_t questId);
virtual bool scenePlayerAddAcceptableQuest(int32_t questId);
virtual bool scenePlayerDelAcceptableQuest(int32_t questId);
virtual bool openScene(int32_t sceneId);
virtual bool joinBattle();
virtual bool finishBattle();
virtual bool transforScene(int32_t sceneId);
virtual bool transforSceneByEntry(int32_t sceneId, int32_t entryId);
virtual bool backHomeScene();
virtual bool sceneLoaded();
virtual bool move(COM_FPosition& pos);
virtual bool moveToNpc(int32_t npcid);
virtual bool moveToNpc2(NpcType type);
virtual bool moveToZone(int32_t sceneId, int32_t zoneId);
virtual bool autoBattle();
virtual bool stopMove();
virtual bool addFollow(int32_t scenePlayerId);
virtual bool delFollow(int32_t scenePlayerId);
virtual bool delFollows();
virtual bool addFollows(std::vector< int32_t >& scenePlayers);
virtual bool setEntryFlag(int32_t scenePlayerId, bool isFlag);
virtual bool addNpc(int32_t npcid);
virtual bool delNpc(int32_t npcid);
virtual bool findDynamicNpc(int32_t npcId);
