virtual bool addExp(uint32_t playerId, uint32_t exp);
virtual bool addMoney(uint32_t playerId, int32_t money);
virtual bool addDiamond(uint32_t playerId, int32_t diamond);
virtual bool openGM(uint32_t playerId);
virtual bool closeGM(uint32_t playerId);
virtual bool noTalkPlayer(uint32_t playerId, uint32_t time);
virtual bool sealPlayer(uint32_t playerId);
virtual bool kickPlayer(uint32_t playerId);
virtual bool openTalkPlayer(uint32_t playerId);
virtual bool unsealPlayer(uint32_t playerId);
virtual bool sendMailAllOnline(COM_Mail& mail, int32_t lowLevel, int32_t highLevel, int64_t lowRegTime, int64_t highRegTime);
virtual bool gmtNotice(NoticeSendType bType, std::string& note, uint64_t thetime, int64_t itvtime);
virtual bool setChargeTotal(COM_ADChargeTotal& data);
virtual bool setChargeEvery(COM_ADChargeEvery& data);
virtual bool setDiscountStore(COM_ADDiscountStore& data);
virtual bool setLoginTotal(COM_ADLoginTotal& data);
virtual bool setHotRole(COM_ADHotRole& data);
virtual bool setEmployeeActivity(COM_ADEmployeeTotal& data);
virtual bool setMinGiftBagActivity(COM_ADGiftBag& data);
virtual bool setZhuanpanActivity(COM_ZhuanpanData& data);
virtual bool setIntegralshop(COM_IntegralData& data);
virtual bool makeOrder(uint32_t playerId, SGE_GmtOrder& order);
virtual bool doScript(std::string& script);
virtual bool playerDoScript(uint32_t playerId, std::string& script);
