virtual bool queryPlayerSimpleInformation(std::string& username, int32_t serverId);
virtual bool queryPlayer(std::string& username, int32_t playerId);
virtual bool createPlayer(std::string& username, SGE_DBPlayerData& inst, int32_t serverId);
virtual bool updatePlayer(std::string& username, SGE_DBPlayerData& inst);
virtual bool deletePlayer(std::string& playername);
virtual bool queryPlayerById(std::string& name, int32_t instId, int32_t where);
virtual bool insertEndlessStair(int32_t rank, std::string& name);
virtual bool updateEndlessStair(int32_t rank, std::string& name);
virtual bool createBaby(std::string& playername, COM_BabyInst& inst, bool isToStorage);
virtual bool deleteBaby(std::string& playername, int32_t babyInstId);
virtual bool updateBaby(COM_BabyInst& inst);
virtual bool updateBabys(std::string& playername, std::vector< COM_BabyInst >& babys);
virtual bool queryBabyById(std::string& name, uint32_t instid);
virtual bool createEmployee(std::string& playername, COM_EmployeeInst& inst);
virtual bool deleteEmployee(std::string& playername, std::vector< uint32_t >& instIds);
virtual bool updateEmployee(COM_EmployeeInst& inst);
virtual bool queryEmployeeById(std::string& name, uint32_t instid);
virtual bool insertMail(COM_Mail& mail);
virtual bool insertMailAll(COM_Mail& mail);
virtual bool insertMailByRecvs(COM_Mail& mail, std::vector< std::string >& recvs);
virtual bool fatchMail(std::string& recvName, int32_t mailId);
virtual bool delMail(std::string& recvName, int32_t mailId);
virtual bool updateMail(COM_Mail& mail);
virtual bool insertGuild(COM_Guild& guild, COM_GuildMember& guildMember);
virtual bool updateGuildRequestList(uint32_t guildId, std::vector< COM_GuildRequestData >& data);
virtual bool createGuildMember(COM_GuildMember& guildMember);
virtual bool delGuild(int32_t guildId);
virtual bool updateGuildNotice(uint32_t guildId, std::string& notice);
virtual bool updateGuild(COM_Guild& guild);
virtual bool updateMemberPosition(int32_t roleId, GuildJob job);
virtual bool updateMemberContribution(int32_t roleId, int32_t contribution);
virtual bool updateGuildStruction(uint32_t guildId, int8_t level, int32_t struction);
virtual bool deleteGuildMember(int32_t playerId);
virtual bool insertActivity(ADType adt, SGE_SysActivity& date);
virtual bool insertLoseCharge(int32_t playerId, SGE_OrderInfo& order);
virtual bool insertEmployeeQuest(uint32_t playerId, SGE_PlayerEmployeeQuest& data);
virtual bool delEmployeeQuest(uint32_t playerId);
virtual bool deleteEndlessStair(std::string& name);
