virtual bool joinScene(COM_SceneInfo& info);
virtual bool move2(COM_FPosition& pos);
virtual bool cantMove();
virtual bool transfor2(COM_FPosition& pos);
virtual bool autoBattleResult(bool isOk);
virtual bool zoneJoinBattle(int32_t zoneId);
virtual bool playerAddNpc(std::vector< int32_t >& npcs);
virtual bool playerDelNpc(std::vector< int32_t >& npcs);
virtual bool talkedNpc(int32_t npcid);
virtual bool findDynamicNpcOK(int32_t npcid, bool hasnpc);
