virtual bool syncGlobalGuid(uint32_t id);
virtual bool syncContactInfo(std::vector< SGE_ContactInfoExt >& info);
virtual bool queryPlayerSimpleInformationOk(std::string& username, std::vector< COM_SimpleInformation >& insts, int32_t serverId);
virtual bool queryPlayerOk(std::string& username, SGE_DBPlayerData& player);
virtual bool createPlayerOk(std::string& username, SGE_DBPlayerData& inst, int32_t inDoorId);
virtual bool createPlayerSameName(std::string& username);
virtual bool queryPlayerByIdOK(std::string& playername, SGE_DBPlayerData& inst, int32_t where);
virtual bool queryEndlessStairAllDateOK(std::vector< std::string >& name);
virtual bool queryPlayerByLevelOK(std::vector< COM_ContactInfo >& info);
virtual bool queryPlayerByFFOK(std::vector< COM_ContactInfo >& info);
virtual bool createBabyOK(std::string& playername, COM_BabyInst& inst, bool isToStorage);
virtual bool deleteBabyOK(std::string& playername, int32_t babyInstId);
virtual bool queryBabyByFFOK(std::vector< COM_BabyRankData >& infos);
virtual bool queryBabyByIdOK(std::string& name, COM_BabyInst& inst);
virtual bool UpdateBabysOK(std::string& playername);
virtual bool createEmployeeOK(std::string& playername, COM_EmployeeInst& inst);
virtual bool deleteEmployeeOK(std::string& playername, std::vector< uint32_t >& instIds);
virtual bool queryEmployeeByFFOK(std::vector< COM_EmployeeRankData >& infos);
virtual bool queryEmployeeByIdOK(std::string& name, COM_EmployeeInst& inst);
virtual bool appendMail(std::string& playerName, std::vector< COM_Mail >& mails);
virtual bool insertGuildOK(COM_Guild& guild, COM_GuildMember& guildMember);
virtual bool updateMemberJobOk(int32_t roleId, GuildJob job);
virtual bool syncGuild(std::vector< COM_Guild >& guilds);
virtual bool syncGuildMember(std::vector< COM_GuildMember >& guildMember);
virtual bool fatchActivity(SGE_SysActivity& date);
virtual bool syncEmployeeQuest(std::vector< SGE_PlayerEmployeeQuest >& info);
