version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mlbb-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: 8000_game
      MYSQL_USER: xysk
      MYSQL_PASSWORD: xysk_password
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ../sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - mlbb-network

  mlbb-server:
    image: mlbb-server-runtime:latest
    container_name: mlbb-server-runner
    depends_on:
      mysql-db:
        condition: service_healthy
    command: >
      bash -c " echo 'Waiting for database initialization...'; sleep 5; ./server_start.sh && tail -f /dev/null"
    networks:
      - mlbb-network
    ports:
      - "21000:21000"
    deploy:
      resources:
        limits:
          memory: 8G
    restart: always

networks:
  mlbb-network:
    driver: bridge
